version: '3'

services:
  jupyter:
    image: pytorch:latest
    ports:
      - 8888:8888
    command: bash -c "conda install matplotlib && jupyter notebook --notebook-dir=/data --ip='0.0.0.0' --port=8888  --no-browser --allow-root"
    volumes:
      - /home/laura/Documents/learning/udacity/pytorch_challenge:/data