version: '3'

services:
  jupyter:
    image: continuumio/anaconda
    ports:
      - 8888:8888
    command: bash -c "/opt/conda/bin/conda install jupyter -y --quiet && /opt/conda/bin/jupyter notebook --notebook-dir=/data --ip='*' --port=8888  --no-browser --allow-root"
    volumes:
      - /home/laura/Documents/learning/udacity/pytorch_challenge:/data